ALTER TYPE "ExportJobStatus" ADD VALUE IF NOT EXISTS 'RUNNING';

ALTER TABLE "ExportJob"
ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastError" TEXT;
