export const PermissionsList = {
  BUSINESS_READ: 'business.read',
  BUSINESS_UPDATE: 'business.update',
  BUSINESS_DELETE: 'business.delete',
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DEACTIVATE: 'users.deactivate',
  ROLES_READ: 'roles.read',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  CATALOG_READ: 'catalog.read',
  CATALOG_WRITE: 'catalog.write',
  STOCK_READ: 'stock.read',
  STOCK_WRITE: 'stock.write',
  TRANSFERS_READ: 'transfers.read',
  TRANSFERS_WRITE: 'transfers.write',
  SALES_READ: 'sales.read',
  SALES_WRITE: 'sales.write',
  PURCHASES_READ: 'purchases.read',
  PURCHASES_WRITE: 'purchases.write',
  SUPPLIERS_READ: 'suppliers.read',
  SUPPLIERS_WRITE: 'suppliers.write',
  EXPENSES_READ: 'expenses.read',
  EXPENSES_WRITE: 'expenses.write',
  REPORTS_READ: 'reports.read',
  EXPORTS_WRITE: 'exports.write',
  AUDIT_READ: 'audit.read',
  OFFLINE_READ: 'offline.read',
  OFFLINE_WRITE: 'offline.write',
  ATTACHMENTS_WRITE: 'attachments.write',
  CUSTOMERS_VIEW: 'customers.read',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.update',
  CUSTOMERS_EXPORT: 'customers.export',
  CUSTOMERS_VIEW_SENSITIVE: 'customers.sensitive.read',
  CUSTOMERS_ANONYMIZE: 'customers.anonymize',
  PRICE_LISTS_MANAGE: 'price-lists.manage',
  SHIFTS_OPEN: 'shifts.open',
  SHIFTS_CLOSE: 'shifts.close',
  SALE_CREDIT_CREATE: 'sales.credit.create',
  SALE_CREDIT_SETTLE: 'sales.credit.settle',
  RETURN_WITHOUT_RECEIPT: 'sales.return.without-receipt',
  SEARCH_READ: 'search.read',
  SETTINGS_READ: 'settings.read',
  SETTINGS_WRITE: 'settings.write',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTES_READ: 'notes.read',
  NOTES_WRITE: 'notes.write',
  NOTES_MANAGE: 'notes.manage',
  APPROVALS_READ: 'approvals.read',
  APPROVALS_WRITE: 'approvals.write',
  SUBSCRIPTION_READ: 'subscription.read',
  SUBSCRIPTION_REQUEST: 'subscription.request',
} as const;

export type PermissionCode =
  (typeof PermissionsList)[keyof typeof PermissionsList];
